project:
  type: book
  # output-dir: docs

execute:
  freeze: auto
  echo: true

book:
  title: "Learning Python"
  author: "Kasper Munch"
  sidebar:
    search: true
    collapse-level: 1    
    # style: "docked"

  chapters:
    - index.qmd
    - part: "Lecture notes"
      chapters: 
      - lecture_notes/chapters/python/preface.md
      - lecture_notes/chapters/python/before_you_begin.md
      - lecture_notes/chapters/python/appendix_conda_and_pymol.md
      - lecture_notes/chapters/python/writing_a_program.md
      - lecture_notes/chapters/python/dealing_with_values.md
      - lecture_notes/chapters/python/the_order_of_events.md
      - lecture_notes/chapters/python/course_tools.md
      - lecture_notes/chapters/python/controlling_behavior.md
      - lecture_notes/chapters/python/organizing_your_code.md
      - lecture_notes/chapters/python/python_values_are_objects.md
      - lecture_notes/chapters/python/lists.md
      - lecture_notes/chapters/python/dictionaries.md
      - lecture_notes/chapters/python/gluing_values_in_sequence.md
      - lecture_notes/chapters/python/iteration_over_values.md
      - lecture_notes/chapters/python/working_with_data_files.md
      - lecture_notes/chapters/python/data_structures.md
      - lecture_notes/chapters/python/unleash_your_functions.md
      - lecture_notes/chapters/python/testing_your_code.md
      - lecture_notes/chapters/python/your_own_types_of_objects.md
      - lecture_notes/chapters/python/using_code_from_other_files.md
      - lecture_notes/chapters/python/on_the_shoulders_of_giants.md
    - part: "Programming projects"
      chapters:
        - lecture_notes/chapters/project/translation_project.md
        - lecture_notes/chapters/project/folding_project.md
        - lecture_notes/chapters/project/alignment_project.md
        - lecture_notes/chapters/project/codonbias_project.md
        - lecture_notes/chapters/project/hiv_project.md
        - lecture_notes/chapters/project/seqdist_project.md
        - lecture_notes/chapters/project/orf_project.md
        - lecture_notes/chapters/project/assembly_project.md
    - part: "Supplementary"
      chapters: 
      - supplementary/suppl2024.qmd

crossref:
  sec-prefix: "exercise"

format:
  html:
    theme: 
      - default
      - custom.scss
    toc-depth: 2
    notebook-links: global
    number-sections: false

# website:
#   sidebar:
#     style: "docked"
#     # style: "floating" # default
#     search: true
#     contents:
#       - text: "Introduction"
#         href: introduction.qmd
#       - section: "Basics"
#         href: basics-summary.qmd
#         contents:
#           - index.qmd
#           - basics-knitr.qmd
#           - basics-jupyter.qmd
#       - section: "Layout"
#         contents:
#           - layout.qmd
#           - layout-knitr.qmd
#           - layout-jupyter.qmd
#       - section: advanced.qmd
#         contents:
#           - raw-code.qmd
#           - custom-theme.qmd
#       - acknowlegment.qmd
