project:
  type: book
  # output-dir: docs

execute:
  freeze: auto
  echo: true

book:
  title: "Learning Python"
  author: "Kasper Munch"
  chapters:
    - index.qmd
    - part: "Recordings"
      chapters: 
      - supplementary/suppl2024.qmd

format:
  html:
    theme: 
      - default
      - custom.scss
    toc-depth: 2
    notebook-links: global
    number-sections: false

